//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObjetosDeNegocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientesDatosAdicionales
    {
        public int ID { get; set; }
        public int IDCliente { get; set; }
        public string Domicilio { get; set; }
        public string Email { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
