//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObjetosDeNegocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        public int ID { get; set; }
        public int MesaSalon { get; set; }
        public int Plato { get; set; }
        public string Adicional1 { get; set; }
        public string Adicional2 { get; set; }
        public string Adicional3 { get; set; }
    
        public virtual MesasPorSalon MesasPorSalon { get; set; }
        public virtual Platos Platos { get; set; }
    }
}
